export type ReelCategory = "english" | "programming";

export type ReelType = "word" | "rule" | "dialogue" | "code" | "fact";

export type ReelCard = {
  id: string;
  type: ReelType;
  category: ReelCategory;
  title: string;
  word?: string;
  transcription?: string;
  translation?: string;
  example?: string;
  lines?: string[];
  dialogue?: { speaker: string; text: string }[];
  code?: string;
  explanation?: string;
  fact?: string;
  question: string;
  options: string[];
  correct: number;
  xp: number;
};

export const reels: ReelCard[] = [
  {
    id: "en-word-ambitious",
    type: "word",
    category: "english",
    title: "Слово дня",
    word: "Ambitious",
    transcription: "/aem-bish-uhs/",
    translation: "Амбициозный",
    example: "Ayperi is ambitious and studies English every evening.",
    question: "Что означает ambitious?",
    options: ["Ленивый", "Амбициозный", "Грустный", "Случайный"],
    correct: 1,
    xp: 15,
  },
  {
    id: "py-range",
    type: "code",
    category: "programming",
    title: "Код за минуту",
    code: "for i in range(3):\n    print(i)",
    explanation: "range(3) создает числа от 0 до 2.",
    question: "Что выведет программа?",
    options: ["1 2 3", "0 1 2", "0 1 2 3", "Ошибку"],
    correct: 1,
    xp: 15,
  },
  {
    id: "en-rule-present-simple",
    type: "rule",
    category: "english",
    title: "Правило за 60 секунд",
    lines: ["Present Simple = привычки.", "I drink tea every morning.", "He/She/It получает -s: Madina drinks tea."],
    example: "Bekbolot plays football after school.",
    question: "Как правильно?",
    options: ["She play chess", "She plays chess", "She playing chess", "She played chess"],
    correct: 1,
    xp: 15,
  },
  {
    id: "cs-variable-box",
    type: "fact",
    category: "programming",
    title: "Факт о коде",
    fact: "Переменная похожа на коробку с названием: положил значение, потом используешь по имени.",
    question: "Что хранит переменная?",
    options: ["Только картинки", "Значение", "Только ошибки", "Wi-Fi"],
    correct: 1,
    xp: 15,
  },
  {
    id: "en-dialogue-bazaar",
    type: "dialogue",
    category: "english",
    title: "Диалог",
    dialogue: [
      { speaker: "Мааанай", text: "Hi, how much is this somsa?" },
      { speaker: "Seller", text: "It is 50 soms." },
      { speaker: "Мааанай", text: "Great, I will take two." },
    ],
    question: "Что лучше ответить продавцу?",
    options: ["I will take two.", "I am from Osh.", "It is raining.", "No homework."],
    correct: 0,
    xp: 15,
  },
  {
    id: "py-print",
    type: "code",
    category: "programming",
    title: "Python: print",
    code: "city = 'Bishkek'\nprint('Hello', city)",
    explanation: "print выводит текст и значения на экран.",
    question: "Что появится на экране?",
    options: ["Hello Bishkek", "city", "Ошибка", "Hello city"],
    correct: 0,
    xp: 15,
  },
  {
    id: "en-word-reliable",
    type: "word",
    category: "english",
    title: "Слово дня",
    word: "Reliable",
    transcription: "/ri-lai-uh-buhl/",
    translation: "Надежный",
    example: "Alihan is a reliable friend during group projects.",
    question: "Reliable значит...",
    options: ["Надежный", "Шумный", "Дорогой", "Пустой"],
    correct: 0,
    xp: 15,
  },
  {
    id: "cs-if",
    type: "rule",
    category: "programming",
    title: "Условие за 60 секунд",
    lines: ["if = если.", "Если балл больше 70, урок открыт.", "Иначе Маанай дает подсказку."],
    code: "score = 86\nif score >= 70:\n    print('Unlocked')",
    question: "Когда сработает if?",
    options: ["Когда условие истинно", "Всегда", "Никогда", "Только ночью"],
    correct: 0,
    xp: 15,
  },
  {
    id: "en-fact-v",
    type: "fact",
    category: "english",
    title: "Факт о языке",
    fact: "В английском порядок слов важен: I like plov и Plov likes me имеют совсем разный смысл.",
    question: "Что особенно важно в английском предложении?",
    options: ["Порядок слов", "Цвет ручки", "Размер шрифта", "Погода"],
    correct: 0,
    xp: 15,
  },
  {
    id: "py-list",
    type: "code",
    category: "programming",
    title: "Списки",
    code: "foods = ['plov', 'somsa', 'kurut']\nprint(foods[0])",
    explanation: "Индексы в Python начинаются с 0.",
    question: "Что выведет код?",
    options: ["somsa", "plov", "kurut", "0"],
    correct: 1,
    xp: 15,
  },
  {
    id: "en-word-confident",
    type: "word",
    category: "english",
    title: "Слово дня",
    word: "Confident",
    transcription: "/kon-fi-dent/",
    translation: "Уверенный",
    example: "Nigora feels confident speaking English in class.",
    question: "Confident значит...",
    options: ["Уверенный", "Голодный", "Медленный", "Сломанный"],
    correct: 0,
    xp: 15,
  },
  {
    id: "cs-loop",
    type: "rule",
    category: "programming",
    title: "Цикл за 60 секунд",
    lines: ["Цикл повторяет действие.", "for повторяет известное число раз.", "while повторяет, пока условие истинно."],
    question: "Что делает цикл?",
    options: ["Повторяет действия", "Удаляет проект", "Включает микрофон", "Рисует фото"],
    correct: 0,
    xp: 15,
  },
  {
    id: "en-dialogue-intro",
    type: "dialogue",
    category: "english",
    title: "Знакомство",
    dialogue: [
      { speaker: "Мааанай", text: "What is your name?" },
      { speaker: "Student", text: "My name is Asan." },
      { speaker: "Мааанай", text: "Nice to meet you!" },
    ],
    question: "Как сказать: Меня зовут Асан?",
    options: ["I am old", "My name is Asan", "I from Asan", "Name my Asan"],
    correct: 1,
    xp: 15,
  },
  {
    id: "py-function",
    type: "code",
    category: "programming",
    title: "Функция",
    code: "def greet(name):\n    return 'Salam, ' + name\n\nprint(greet('Madina'))",
    explanation: "Функция хранит действие, которое можно вызвать много раз.",
    question: "Что вернет greet('Madina')?",
    options: ["Salam, Madina", "name", "Ошибка", "Madina Salam"],
    correct: 0,
    xp: 15,
  },
  {
    id: "en-rule-article",
    type: "rule",
    category: "english",
    title: "A или An",
    lines: ["a ставим перед согласным звуком.", "an ставим перед гласным звуком.", "an apple, a book, a university."],
    question: "Выбери правильно:",
    options: ["a apple", "an apple", "an book", "a orange"],
    correct: 1,
    xp: 15,
  },
  {
    id: "cs-boolean",
    type: "fact",
    category: "programming",
    title: "Факт о boolean",
    fact: "Boolean хранит только два состояния: True или False. Как светофор: можно идти или нельзя.",
    question: "Какие значения бывают у boolean?",
    options: ["True/False", "1/2/3", "red/blue", "city/name"],
    correct: 0,
    xp: 15,
  },
  {
    id: "en-word-curious",
    type: "word",
    category: "english",
    title: "Слово дня",
    word: "Curious",
    transcription: "/kyoor-ee-uhs/",
    translation: "Любопытный",
    example: "Saltanat is curious about how apps are built.",
    question: "Curious значит...",
    options: ["Любопытный", "Сонный", "Высокий", "Соленый"],
    correct: 0,
    xp: 15,
  },
  {
    id: "py-input",
    type: "code",
    category: "programming",
    title: "Ввод",
    code: "name = input('Name: ')\nprint('Welcome', name)",
    explanation: "input ждет текст от пользователя.",
    question: "Что делает input?",
    options: ["Получает ввод", "Удаляет файл", "Рисует кнопку", "Считает XP"],
    correct: 0,
    xp: 15,
  },
  {
    id: "en-fact-th",
    type: "fact",
    category: "english",
    title: "Факт о произношении",
    fact: "Звук th не похож на с или з. Язык мягко касается зубов: think, three, thanks.",
    question: "Как тренировать th?",
    options: ["Язык к зубам", "Кричать громче", "Не открывать рот", "Ставить r"],
    correct: 0,
    xp: 15,
  },
  {
    id: "cs-algorithm",
    type: "rule",
    category: "programming",
    title: "Алгоритм",
    lines: ["Алгоритм = точные шаги.", "Например: купить лепешку, оплатить, забрать сдачу.", "Компьютеру нужны такие же ясные инструкции."],
    question: "Что такое алгоритм?",
    options: ["Последовательность шагов", "Картинка", "Пароль", "Музыка"],
    correct: 0,
    xp: 15,
  },
];
